### ISSUE TITLE
Geolocalisation with georeferenced background map

### ISSUE THREAD

**Issue by citrulluslanatus** [otacke/h5p-game-map#101]
It would be a superb extension (although probably very time-consuming and costly) if a kind of location visualisation / geolocalisation (for devices with GPS) were possible, so that your own location could be displayed on a georeferenced background map. This would enable outdoor activities comparable to e.g. geocaching directly in the terrain or additional information in e.g. nature reserves. 

Maybe something for the distant future if some major funding pops up :).

**Comment by otacke** [comment]
Not something that I'd consider at all for GameMap, sorry. That feature would better be suited for AR Scavenger.

**Comment by citrulluslanatus** [comment]
Okay. I'll habe to improve my JavaScript skills then :). I'll get back to you in about 10 years.
