### ISSUE TITLE
"You lost all your lives please try again" after having obtained max score

### ISSUE THREAD

**Issue by falcon-git** [otacke/h5p-game-map#45]
After having obtained max score on "https://www.olivertacke.de/labs/wp-admin/admin-ajax.php?action=h5p_embed&id=146" I continued playing and lost my last life. I got the "You lost all your lives please try again" message. Frustrating me a bit as I would have expected to not loose more lives after having obtained max score. I.e. that I would be in explore mode.

After having received the lost all your lives message I got the "Congratulations you made it" screen, which I guess I liked better than having to try again, but also felt weird as the previous screen declared me as dead and having to start over :)

Steps to reproduce:
 - Obtain full score
 - Continue playing and loose all your lives

**Comment by otacke** [comment]
@falcon-git That's the risk of life when further gambling after having received a max score (scores are independent of lifes). What's your suggestion acrually?
- Becoming "invincible" once max score has been reached?
- Fixing the end screen message?

**Comment by otacke** [comment]
Fixed by https://github.com/otacke/h5p-game-map/pull/47
- Will warn the user that he/she may still lose lifes
- Fix end screen for full score but no lifes left
