### ISSUE TITLE
Position stage labels on top of all stage icons (map elements)

### ISSUE THREAD

**Issue by dosse** [otacke/h5p-game-map#64]
Hi, thank you for this excellent engaging game map H5P content, which greatly enriches one of my training courses (preparation work currently still in progress: https://academy.siscc.org/courses/disseminating-data-with-an-optimised-end-user-experience/).

Currently, the stage labels (on mouse-over) are shown on top of all _previous_ stage icons (map elements). Unfortunately, in one of my game maps, the stages are placed in a way where later stages cover the labels of previous stages, which become unreadable.

Example:   
![image](https://github.com/otacke/h5p-game-map/assets/1862608/a5f24b31-1188-49a1-8344-c857b04509b3)

Would it please be possible to position stage labels always on top of _all_ stage icons (rather than only the _previous_ ones)?

Note:   
The issue doesn't happen in the content editor or the H5P admin interface, according to my findings thanks to the larger map size. Indeed, the above image is made when the user takes the course and where the course content is limited to a `max-width: 700px;`. When changing this value to `max-width: 1000px;` then the issue strangely disappears:  
![image](https://github.com/otacke/h5p-game-map/assets/1862608/51dd041b-5fef-4235-8f3a-c9b1b3ac2a34)

Final comment:  
It would be great also if the label size allowed for a little longer texts.

Thanks in advance!

**Comment by otacke** [comment]
Hi Jens!

Thanks a lot for reporting. I have fixed the issue with the label tooltips in https://github.com/otacke/h5p-game-map/commit/1f03cd5c6dff2b43dffd1af1dc3bcc0b3da9e939. The fix will be part of the next release. Don't know when H5P Group will update their version on the H5P Hub, however.

The label size will remain as is for now, I think.

Best,
Oliver
