### ISSUE TITLE
Stage content cryptex

### ISSUE THREAD

**Issue by glavca2000** [otacke/h5p-game-map#87]
Add Stage content Cryptex
Admn sets password numbers or letters
User must find matching password to open Cryptex
When cryptex is opened 1 point is awardwed and optional message, video or sound is played

**Comment by otacke** [comment]
@glavca2000 If I understand you correctly, you can achieve this today already. You can make your password the solution to a Fill-in-the-Blanks exercise. Just hide the password in some other stage. Or did I misunderstand what you have in mind?

**Comment by glavca2000** [comment]
Yes, that is one of the solutions. Tnx.
I there any option to add embed code into text field?

**Comment by otacke** [comment]
@glavca2000 No, this is not possible but not related to GameMap in particular, but to the respective subcontent type that you're using.
