### ISSUE TITLE
typos in de.json

### ISSUE THREAD

**Issue by hanghuhn** [otacke/h5p-game-map#92]
Hello,

there are two typos in the German language file:

```
"label": "Nutzerinnen und Nutzer können hier starten",
                    "description": "Wenn ängewählt, können Nutzerinnen und Nutzer bei dieser Etappe starten. Wenn bei keinre Etappe oder mehr als einer gestartet werden kann, wird die Startetappe zufällig bestimmt."
```

the desription should be:
"Wenn **angewählt**, können Nutzerinnen und Nutzer bei dieser Etappe starten. Wenn bei **keiner** Etappe oder mehr als einer gestartet werden kann, wird die Startetappe zufällig bestimmt."

**Comment by otacke** [comment]
Fixed, thanks. Feel free to contribute these changes as a pull request next time.
